spring.application.name=task-manager

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=tareas_db;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
 
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL:false}

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true
management.info.env.enabled=true

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
app.security.username=${APP_SECURITY_USERNAME}
app.security.password=${APP_SECURITY_PASSWORD}
app.security.roles=${APP_SECURITY_ROLES:USER}
