name: CI

on:
  push:
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - run: chmod +x mvnw
      - run: ./mvnw verify
      - name: Build Docker image
        run: docker build --tag ghcr.io/sergiog22/task-manager:${{ github.sha }} .
      
      - name: Push Docker image
        run: docker push ghcr.io/sergiog22/task-manager:${{ github.sha }}